### PR TITLE
added python lint check in github actions

### PR DESCRIPTION
**Pull request by modernpacifist**

### CODE REVIEW

**Review by tmshv — CHANGES_REQUESTED** [review]
very interesting

will be better if action will drop a comment with listing errors 

what do you think?

**Comment by modernpacifist** [comment]
well yes, would be cool

**Review by tmshv — APPROVED** [review]
wow that's cool

**Comment by modernpacifist** [comment]
added quantities of errors/warnings in the end of the comments

**Comment by modernpacifist** [comment]
Let's merge it now with raw version, I will refactor it later.

**Review by tmshv — APPROVED** [review]
next time write informative commit message plz

**Pull request merged**
